name: 'Terraform GitHub Actions'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  tf_version: '3.52.0'
  tf_working_dir: '.'
jobs:
  terraform:
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write' 
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      # actions/checkout MUST come before auth
      - name: checkout
        uses: actions/checkout@v3

      - name: Set GCP environment
        id: set_gcp_env
        run: export BRANCH_NAME=$(echo ${GITHUB_BASE_REF#refs/heads/})
        shell: bash

      - name: Authenticate to Google Cloud
        id: authenticate_to_gcp
        uses: google-github-actions/auth@v0.7.3
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOADIDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_NAME }}
          token_format: 'access_token'
          access_token_lifetime: '300s'          


      - name: set GCP project
        id: config_project
        run: gcloud config set project vivid-rush-227416

      - name: "Set gcloud auth"
        id: decrypt_SA
        run: gcloud auth login --brief --cred-file="${{ steps.authenticate_to_gcp.outputs.credentials_file_path }}" 
        #working-directory: "environments/${{ env.BRANCH_NAME }}"

      - name: "Terraform Init"
        id: terraform_init
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.tf_version }}
          terraform_wrapper: "false"
          tf_actions_subcommand: init
        run: terraform init
        #env:
         # GCP_SA_KEY: ${{ secrets.GCP_SA_KEY}}
      - name: "Terraform Validate"
        id: terraform_validate
        uses: ops18/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_comment: "false"
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_subcommand: validate
        #env:
         # GCP_SA_KEY: ${{ secrets.GCP_SA_KEY}} 
      - name: "Terraform Plan"
        id: terraform_plan
        uses: ops18/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_comment: "false"
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_subcommand: plan
        #env:
         # GCP_SA_KEY: ${{ secrets.GCP_SA_KEY}}
          
      - name: "Terraform Apply"
        uses: ops18/terraform-github-actions@master
        id: terraform_apply
        with:
          tf_actions_version: ${{ env.TERRAFORM_VERSION }}
          tf_actions_comment: "false"
          tf_actions_working_dir: environments/${{ env.BRANCH_NAME }}
          tf_actions_subcommand: apply
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY}}